"""
scenario.py - THE STRATEGIST (part 2): what-if simulator.

Takes the trained final model and the 13 future weeks, changes one business lever,
re-forecasts, and reports the demand change in units:

  * promotion intensity  x0 (no promos) ... x2 (double)  -> promo response curve
  * promo uplift decomposition: baseline (no promos) vs promo-driven units, by family
  * oil price shock +-15% (macro sensitivity)

Caveat: the model learned associations from history. Effects are most reliable
inside the range seen in the data (roughly x0.5 - x1.5 promo intensity).
"""
from __future__ import annotations

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import config as C
from src import models as M
from src.eda import SERIES, INK2, AXIS
from src.forecast import future_rows


# =============================================================================== levers
def set_promo(df: pd.DataFrame, multiplier: float) -> pd.DataFrame:
    d = df.copy()
    d["k_promo_sum"] = d["k_promo_sum"] * multiplier
    if multiplier == 0:
        d["k_promo_days"] = 0
    d["k_promo_vs_usual"] = np.log1p(d["k_promo_sum"]) - np.log1p(d["o_promo_ma13"].fillna(0))
    return d


def set_oil(df: pd.DataFrame, change: float) -> pd.DataFrame:
    d = df.copy()
    d["o_oil"] = d["o_oil"] * (1 + change)
    for c in ("o_oil_chg4", "o_oil_chg13"):
        d[c] = (1 + d[c]) * (1 + change) - 1
    return d


SCENARIOS = {
    "Base forecast": lambda d: d,
    "Promotions +20%": lambda d: set_promo(d, 1.2),
    "Promotions -20%": lambda d: set_promo(d, 0.8),
    "No promotions": lambda d: set_promo(d, 0.0),
    "Oil price -15%": lambda d: set_oil(d, -0.15),
    "Oil price +15%": lambda d: set_oil(d, 0.15),
}


def _save(fig, name):
    fig.tight_layout()
    fig.savefig(C.SCENARIO_DIR / name, dpi=130)
    plt.close(fig)
    return name


# =============================================================================== runner
def run_scenarios(sup: pd.DataFrame) -> pd.DataFrame:
    model = M.GlobalLGBM.load(C.MODEL_DIR)
    fut = future_rows(sup)
    fam = fut[C.SKU_COL].astype(str).to_numpy()

    preds = {name: model.predict(fn(fut)) for name, fn in SCENARIOS.items()}
    base = preds["Base forecast"].sum()
    summary = pd.DataFrame({
        "total units (13 wks)": {k: v.sum() for k, v in preds.items()},
        "change vs base (units)": {k: v.sum() - base for k, v in preds.items()},
        "change vs base (%)": {k: v.sum() / base - 1 for k, v in preds.items()},
    })
    summary.to_csv(C.SCENARIO_DIR / "scenario_summary.csv")

    # by family for the promo scenarios + uplift decomposition
    by_fam = pd.DataFrame({k: pd.Series(v).groupby(fam).sum() for k, v in preds.items()})
    by_fam["promo uplift units"] = by_fam["Base forecast"] - by_fam["No promotions"]
    by_fam["promo uplift % of forecast"] = by_fam["promo uplift units"] / by_fam["Base forecast"]
    by_fam["+20% promo effect %"] = by_fam["Promotions +20%"] / by_fam["Base forecast"] - 1
    by_fam = by_fam.sort_values("Base forecast", ascending=False)
    by_fam.to_csv(C.SCENARIO_DIR / "scenario_by_family.csv")

    # promo response curve
    mults = [0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]
    curve = pd.Series({m: model.predict(set_promo(fut, m)).sum() for m in mults})
    curve_pct = curve / curve.loc[1.0] - 1
    curve.rename("total units").to_csv(C.SCENARIO_DIR / "promo_response_curve.csv")

    charts = [_chart_summary(summary), _chart_curve(curve_pct), _chart_uplift(by_fam)]
    uplift_total = base - preds["No promotions"].sum()
    top_up = by_fam.loc[by_fam["Base forecast"] > by_fam["Base forecast"].sum() * 0.005] \
        .sort_values("promo uplift % of forecast", ascending=False).head(5)

    s_md = summary.copy()
    s_md["total units (13 wks)"] = s_md["total units (13 wks)"].map("{:,.0f}".format)
    s_md["change vs base (units)"] = s_md["change vs base (units)"].map("{:+,.0f}".format)
    s_md["change vs base (%)"] = s_md["change vs base (%)"].map("{:+.2%}".format)
    f_md = by_fam[["Base forecast", "No promotions", "promo uplift units", "promo uplift % of forecast",
                   "+20% promo effect %"]].head(15).copy()
    for c in ["Base forecast", "No promotions", "promo uplift units"]:
        f_md[c] = f_md[c].map("{:,.0f}".format)
    for c in ["promo uplift % of forecast", "+20% promo effect %"]:
        f_md[c] = f_md[c].map("{:+.1%}".format)

    md = f"""# Scenario / sensitivity analysis

_Auto-generated by `python main.py --step scenario`. Each scenario changes one lever for all 13 future
weeks and re-runs the final model; everything else is held fixed._

## Summary

{s_md.to_markdown()}

## Baseline vs promotion-driven demand

Of the {base:,.0f} units forecast, about **{uplift_total:,.0f} units ({uplift_total / base:.1%})** are
attributed to promotions (base forecast minus the same forecast with no promotions). Families with the
highest share of promo-driven volume: {', '.join(f'{i} ({r["promo uplift % of forecast"]:.0%})' for i, r in top_up.iterrows())}.

{f_md.to_markdown()}

## Promotion response curve

{pd.DataFrame({'promo intensity (x current plan)': curve.index, 'total units': curve.map('{:,.0f}'.format).values, 'vs plan': curve_pct.map('{:+.2%}'.format).values}).to_markdown(index=False)}

""" + "\n".join(f"![{c}]({c})" for c in charts) + """

**How to read this.** The model reflects historical associations, not a controlled experiment.
Promo effects outside ~x0.5-x1.5 extrapolate beyond what the stores have done before; oil effects
are small because oil enters only as a slow macro signal known at the forecast origin.
"""
    (C.SCENARIO_DIR / "scenario_report.md").write_text(md, encoding="utf-8")
    print(f"  - scenario_report.md written to {C.SCENARIO_DIR}")
    return summary


# =============================================================================== charts
def _chart_summary(summary: pd.DataFrame) -> str:
    s = summary.drop("Base forecast")["change vs base (%)"].iloc[::-1]
    fig, ax = plt.subplots(figsize=(8, 3.4))
    ax.barh(s.index, s.values * 100, color=[SERIES[0] if v > 0 else SERIES[1] for v in s.values], height=0.6)
    ax.axvline(0, color=AXIS, lw=1)
    for i, v in enumerate(s.values):
        ax.text(v * 100, i, f" {v:+.2%} ", va="center", ha="left" if v >= 0 else "right", fontsize=8, color=INK2)
    ax.grid(axis="y", visible=False)
    ax.set_xlabel("Change in 13-week total units vs base forecast (%)")
    ax.set_title("What-if scenarios")
    return _save(fig, "scn_01_summary.png")


def _chart_curve(curve_pct: pd.Series) -> str:
    fig, ax = plt.subplots(figsize=(8, 3.6))
    ax.plot(curve_pct.index, curve_pct.values * 100, color=SERIES[0], marker="o", ms=5)
    ax.axvspan(0.5, 1.5, color=AXIS, alpha=0.25, lw=0)
    ax.text(1.0, ax.get_ylim()[0], "range seen in history", ha="center", va="bottom", fontsize=8, color=INK2)
    ax.axhline(0, color=AXIS, lw=1)
    ax.set_xlabel("Promotion intensity (x current plan)")
    ax.set_ylabel("Units vs plan (%)")
    ax.set_title("Promotion response curve (chain total, 13 weeks)")
    return _save(fig, "scn_02_promo_curve.png")


def _chart_uplift(by_fam: pd.DataFrame) -> str:
    top = by_fam.head(12)["promo uplift % of forecast"].iloc[::-1]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    ax.barh(top.index, top.values * 100, color=SERIES[0], height=0.6)
    for i, v in enumerate(top.values):
        ax.text(v * 100, i, f" {v:.1%}", va="center", fontsize=8, color=INK2)
    ax.grid(axis="y", visible=False)
    ax.set_xlabel("Share of forecast attributed to promotions (%)")
    ax.set_title("Promo-driven share of demand, 12 largest families")
    return _save(fig, "scn_03_promo_uplift_by_family.png")
